#!/bin/bash
#
#
#
#
#
#
printf "[Info] Kill termux-x11 and pulseaudio\n"
killall -9 termux-x11 pulseaudio virgl_test_server_android termux-wake-lock
am start --user 0 -n com.termux.x11/com.termux.x11.MainActivity
XDG_RUNTIME_DIR=${TMPDIR}
printf "[Info] Launching termux-x11\n"
termux-x11 :0 -ac &
printf "[Info] Launching pulseaudio\n"
pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1
pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1

virgl_test_server_android &
printf "[Info] Launching xfce4 desktop\n"
sleep 1

proot-distro login debian --user debian --shared-tmp -- bash -c "export DISPLAY=:0 PULSE_SERVER=tcp:127.0.0.1; dbus-launch --exit-with-session startxfce4"
