#!/usr/bin/env bash
export INI=F
export WH=/opt/chat
export INFF="Write by HKArvin123 in 3/28/2025"
until [ $INI == "true" ]
do
	clear
	printf "Info: $INFF\n"
	printf "chose your file\n"
	ls $WH
	read -p "Enter file name: " EN
	if [ $EN == remove ]; then
		clear
		printf "Enter file name.\n"
		read -p "Enter: " RM
		rm $WH/$RM
		export INFF="File $RM have been removed"
	elif [ $EN == make ]; then
		clear
		printf "Enter file name.\n"
		read -p "Enter: " MK
		touch $WH/$MK
		export INFF="File $MK have been created"
	else
		if [ ! -f $WH/$EN ]; then
			export INFF="File $EN not found."
		else
			export INI=true
		fi
	fi
done
clear
printf "Press enter to reflash. Type exit to exit\n"
tail -44 $WH/$EN
read -p "Enter: " CMD
until [ $CMD == exit ]
do
	if [ $CMD == $NT ]; then
		clear
		printf "exit using ^C\n"
		tail -44 $WH/$EN
	else
		echo "$USER $(date +"%Y-%m-%d")" >> $WH/$EN
		echo "$CMD" >> $WH/$EN
		echo "============================================" >> $WH/$EN
	fi
	clear
	printf "exit using ^C\n"
	tail -44 $WH/$EN
	read -p "Enter: " CMD
done
clear
exit 0
