#!/bin/bash
if [[ $EUID -ne 0 ]]; then
	    echo "You must be root to do this." 1>&2
	    exit 0
fi
read -p "Are you sure to install chat tool?[Y/n]" GG
if [ $GG = "Y" ]; then
	if [ ! -f "/usr/bin/git" ]; then
		printf "you need to install git\n"
		read -p "Install git?[Y/n]" RT
	if [ "$RT" = "Y" ]; then
			apk add git
			git clone https://github.com/HKArvin123/somescript-.git
			cd somescript*
			chmod +x *
			mv chat /usr/local/bin/chat
			cd ~
			rm -fr somescript*
	elif [ "$RT" = "y" ];then
			apk add git
			git clone https://github.com/HKArvin123/somescript-.git
			cd somescript*
			chmod +x *
			mv chat /usr/local/bin/chat
			cd ~
			rm -fr somescript*
	else
			printf "Install aborted."
			exit 0
	fi
	else
		git clone https://github.com/HKArvin123/somescript-.git
		cd somescript*
		chmod +x *
		mv chat /usr/local/bin/chat
		cd ~
		rm -fr somescript*
	fi
elif [ $GG = "y" ]; then
	if [ ! -f "/usr/bin/git" ]; then
		printf "you need to install git\n"
		read -p "Install git?[Y/n]" RT
		if [ "$RT" = "Y" ]; then
			apk add git
			git clone https://github.com/HKArvin123/somescript-.git
			cd somescript*
			chmod +x *
			mv chat /usr/local/bin/chat
			cd ~
			rm -fr somescript*
		elif [ "$RT" = "y" ];then
			apk add git
			git clone https://github.com/HKArvin123/somescript-.git
			cd somescript*
			chmod +x *
			mv chat /usr/local/bin/chat
			cd ~
			rm -fr somescript*
		else
			printf "Install aborted."
			exit 0
		fi
	else
		git clone https://github.com/HKArvin123/somescript-.git
		cd somescript*
		chmod +x *
		mv chat /usr/local/bin/chat
		cd ~
		rm -fr somescript*
	fi
else
	printf "Install aborted\n"
	exit
fi