#!/bin/sh

##Setup chinese###
printf "Setting up chinese\n"
echo 'zh_TW.UTF-8 UTF-8' >> /etc/locale.gen
locale-gen
echo "LANG=zh_TW.UTF-8" > /etc/locale.conf


printf "[Info] Install need package."
apt update
apt upgrade
dpkg --add-architecture armhf
apt install git build-essential cmake wget gcc-arm-linux-gnueabihf zenity:armhf libasound*:armhf libstdc++6:armhf mesa*:armhf -y
apt install sudo zsh xfce4 xfce4-goodies dbus-x11 fakeroot -y


##Setup##
cd /etc/zsh/
wget -O zshrc https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc
printf "Root password.\n"
passwd root
printf "Add a user.\n"
useradd -m -g users -G wheel -s /bin/zsh debian
printf "User password.\n"
passwd debian
visudo
su debian

##Clone Box86/64##
printf "cloning box64 and box86\n"
cd ~
mkdir work
cd work
git clone https://github.com/ptitSeb/box86.git
git clone https://github.com/ptitSeb/box64.git

##Build Box86##
printf "Building box86"
cd box86
mkdir build; cd build; cmake .. -DRPI4ARM64=1 -DARM_DYNAREC=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo
make -j$(nproc)
make install
cd ..
printf "done\n"
##END##

##Build Box64##
printf "building box64\n"
cd box64
mkdir build; cd build; cmake .. -DRPI4ARM64=1 -DARM_DYNAREC=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo
make -j$(nproc)
make install
cd ..
printf "done\n"
##END##



####Install Steam######
printf "[Info] Install Steam\n"
cd box86
bash install_steam.sh
