#!/bin/sh

printf "Setting up language.(eng,zh)\n"
printf "不建議使用zh_HK，翻譯不全。\n"
echo 'zh_TW.UTF-8 UTF-8' >> /etc/locale.gen
locale-gen
echo "LANG=zh_TW.UTF-8" > /etc/locale.conf


printf "[Info] Install need package."
apt update
apt upgrade
dpkg --add-architecture armhf
apt install git build-essential cmake wget gcc-arm-linux-gnueabihf zenity:armhf libasound*:armhf libstdc++6:armhf mesa*:armhf -y
apt install sudo zsh xfce4 xfce4-goodies dbus-x11 ssh fakeroot -y


##Setup##
printf "Root password.\n"
passwd root
printf "Add a user.\n"
useradd -m -g users -G wheel -s /bin/zsh debian
rm -fr /etc/sudoers
echo 'root    ALL=(ALL:ALL) ALL' > /etc/sudoers
echo 'debian ALL=(ALL:ALL) ALL' >> /etc/sudoers

printf "[Info] type exit to exit\n"