#!/data/data/com.termux/files/usr/bin/bash
printf "[Info] 安裝 proot-distro\n"
sleep 1
pkg install proot-distro
pkg install x11-repo
pkg install termux-x11-nightly pulseaudio vim  mesa-zink virglrenderer-mesa-zink vulkan-loader-android 
curl -O https://raw.githubusercontent.com/HKArvin123/somescript-/refs/heads/main/2
chmod +x 2
mv 2 startdebian


printf "[Info] 安裝 debian\n"
sleep 1
proot-distro install debian

printf "[Info] 進入debian容器\n"
sleep 1
proot-distro login debian  --shared-tmp --isolated -- bash -c 'bash -c "$(curl -o raw.githubusercontent.com/HKArvin123/somescript-/refs/heads/main/JUSTASCRIPT)"'


proot-distro login debian --user debian --shared-tmp --isolated -- bash -c "curl -fsSL raw.githubusercontent.com/HKArvin123/somescript-/refs/heads/main/installbox"


