#!/bin/bash
#
# file name linksave
# made by hkarvin123
# 2025/2/21 7:40
#
#
WH=$HOME/link
source ~/.bashrc
while [ True ]; do
if [ "$1" = "--add" -o "$1" = "-a"  ]; then
	ADD=$2
        shift 2
	echo $(date +"%Y-%m-%d") >> $WH
	echo "$ADD" >> $WH
	echo "========================================================" >> $WH
	printf "done\n"
	exit
elif [ "$1" = "--clear" -o "$1" = "-c" ]; then
	sudo cp $WH $WH.bak
	sudo rm -fr $WH
	sudo touch $WH
	sudo chmod 777 $WH
	echo "========================================================" >> $WH
	printf "done\n"
	exit
else
	break
fi
done
if [ ! -d "$WH" ];then
	touch $HOME/link
else
	sleep 1
fi
printf "Enter link: "
read CMD
if [ $CMD == clear ];then
	sudo cp $WH $WH.bak
	printf "clearing ...\n"
	sudo rm -fr $WH
	sudo touch $WH
        sudo chmod 777 $WH
	echo "========================================================" >> $WH
	printf "clean done!\n"
else
	echo $(date +"%Y-%m-%d") >> $WH
        echo "$CMD" >> $WH
	echo "========================================================" >> $WH
        printf "done!\n"
fi
